[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
aimax_sender = "7WZnCPM7MiHf1zJ2w24QaXqyjq9rEQSxH3LrEK4E1Da8"
aimax_receiver = "349aLaSDp4bD1G8yy6aMErx446c6dR2FAtmtoDeunD9c"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
