[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
aimax_receiver = "ELmaisX3tBermvPvmcnAEuKYHMatdYA9fuimNkoF7Mhf"
aimax_sender = "8cwnG9txemHdCqAJTunL3rgBDauuVCDntCSwiithzCjo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
