[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
aimax_receiver = "639Y5ToFkcACreQ6APkVo3zjyfPHvW6UP7Vz1Qr6kXDs"
aimax_sender = "5XVazJ8jazYk5Vn89RExHMZvZgGM5Upw1h2P8UUbuMYn"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
